version: "3.9"

services:
  database:
    image: postgres
    container_name: database_fin
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=fin_api
    volumes: 
      - pgdata:/data/postgres
  app:
    build: .
    container_name: fin
    restart: always
    ports: 
      - 3333:3333
      - 9229:9229
    volumes: 
      - .:/usr/app
   


volumes:
  psdata:
    driver: local

